M48
; DRILL file {KiCad 7.0.2} date Wed Jun 21 14:39:46 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-06-21T14:39:46-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.950
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.700
%
G90
G05
T1
X160.554Y-59.539
X165.554Y-59.539
T2
X96.695Y-130.022
X103.495Y-130.022
T3
X88.0Y-58.0
X88.0Y-117.0
X163.0Y-107.19
X182.0Y-58.0
X182.0Y-117.0
T0
M30
